<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\Admin\AdminAuthController;
use App\Http\Controllers\Admin\AdminManagementController;
use App\Http\Controllers\Admin\AdminModuleController;
use App\Http\Controllers\Admin\AuditTrailController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\FeedbackDimensionController;
use App\Http\Controllers\Admin\FeedbackQuestionController;
use App\Http\Controllers\Admin\FeedbackRatingController;
use App\Http\Controllers\Admin\FormTemplateController;
use App\Http\Controllers\Admin\LabRequestController;
use App\Http\Controllers\Admin\ProcessingRequestController;
use App\Http\Controllers\Admin\RddRequestController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\ServiceRequestController;
use App\Http\Controllers\Admin\SiteVisitorController;
use App\Http\Controllers\Admin\TrainingRequestController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\WalkInController;
use App\Http\Middleware\CaptureVisitorsMiddleware;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])
    ->middleware(CaptureVisitorsMiddleware::class)
    ->name('home');
Route::get('walk-in', [WalkInController::class, 'index'])->name('walk-in');
Route::get('walk-in/client', [WalkInController::class, 'findClient'])->name('walk-in.client');
Route::post('walk-in/validate', [WalkInController::class, 'validateDetails'])->name('walk-in.validate');
Route::post('walk-in', [WalkInController::class, 'store'])->name('walk-in.store');
Route::get('book-an-appointment', [AppointmentController::class, 'index'])->name('appointment');
Route::get('book-an-appointment/client', [AppointmentController::class, 'findClient'])->name('appointment.client');
Route::post('book-an-appointment/validate-booking', [AppointmentController::class, 'validateBooking'])->name('appointment.validate-booking');
Route::post('book-an-appointment/validate', [AppointmentController::class, 'validateDetails'])->name('appointment.validate');
Route::post('book-an-appointment', [AppointmentController::class, 'store'])->name('appointment.store');
Route::get('feedback/{token}', [FeedbackController::class, 'show'])->name('feedback.show');
Route::post('feedback/{token}', [FeedbackController::class, 'store'])->name('feedback.store');
Route::get('address/regions', [AddressController::class, 'regions'])->name('address.regions');
Route::get('address/regions/{region}/provinces', [AddressController::class, 'provinces'])->name('address.provinces');
Route::get('address/provinces/{province}/municipalities', [AddressController::class, 'municipalities'])->name('address.municipalities');

Route::get('dashboard', [AdminManagementController::class, 'dashboard'])
    ->middleware(['auth', 'role:superadmin'])
    ->name('dashboard');

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('login', [AdminAuthController::class, 'create'])->name('login');
    Route::post('login', [AdminAuthController::class, 'store'])->middleware('guest')->name('login.store');
    Route::post('logout', [AdminAuthController::class, 'destroy'])->middleware('auth')->name('logout');

    Route::middleware(['auth', 'role:superadmin'])->group(function () {
        Route::get('/', fn () => to_route('dashboard'))->name('dashboard');
        Route::post('delete-challenge', [AdminManagementController::class, 'deleteChallenge'])->name('delete-challenge');
        Route::get('clients/service-requests', [ClientController::class, 'requests'])->name('clients.requests');
        Route::patch('clients/{client}/archive', [ClientController::class, 'archive'])->name('clients.archive');
        Route::patch('clients/{client}/restore', [ClientController::class, 'restore'])->name('clients.restore');
        Route::get('clients', [ClientController::class, 'index'])->name('clients.index');
        Route::get('site-visitors', [SiteVisitorController::class, 'index'])->name('site-visitors');
        Route::get('reports', [ReportController::class, 'index'])->name('reports');
        Route::get('requests', [ServiceRequestController::class, 'index'])->name('requests.index');
        Route::get('requests/{serviceRequest}/logs', [ServiceRequestController::class, 'logs'])->name('requests.logs');
        Route::patch('requests/{serviceRequest}/proceed', [ServiceRequestController::class, 'proceed'])->name('requests.proceed');
        Route::patch('requests/{serviceRequest}/approve-appointment', [ServiceRequestController::class, 'approveAppointment'])->name('requests.approve-appointment');
        Route::patch('requests/{serviceRequest}/cancel-appointment', [ServiceRequestController::class, 'cancelAppointment'])->name('requests.cancel-appointment');
        Route::get('requests/{serviceRequest}/rdd-request', [RddRequestController::class, 'create'])->name('requests.rdd.create');
        Route::post('requests/{serviceRequest}/rdd-request', [RddRequestController::class, 'store'])->name('requests.rdd.store');
        Route::get('requests/{serviceRequest}/rdd-request/attachments/{type}', [RddRequestController::class, 'downloadPaymentAttachment'])->name('requests.rdd.attachment');
        Route::get('requests/{serviceRequest}/rdd-request/pdf', [RddRequestController::class, 'downloadPdf'])->name('requests.rdd.pdf');
        Route::get('requests/{serviceRequest}/rdd-request/payment', [RddRequestController::class, 'editPayment'])->name('requests.rdd.payment.edit');
        Route::post('requests/{serviceRequest}/rdd-request/payment', [RddRequestController::class, 'updatePayment'])->name('requests.rdd.payment.update');
        Route::post('requests/{serviceRequest}/rdd-request/payment/remind', [RddRequestController::class, 'sendPaymentReminder'])->name('requests.rdd.payment.remind');
        Route::get('requests/{serviceRequest}/rdd-request/feedback', [RddRequestController::class, 'editFeedback'])->name('requests.rdd.feedback.edit');
        Route::post('requests/{serviceRequest}/rdd-request/feedback/remind', [RddRequestController::class, 'sendFeedbackReminder'])->name('requests.rdd.feedback.remind');
        Route::post('requests/{serviceRequest}/rdd-request/feedback/generate-link', [RddRequestController::class, 'generateFeedbackLink'])->name('requests.rdd.feedback.generate-link');
        Route::get('requests/{serviceRequest}/rdd-request/feedback/responses/{feedbackLink}', [RddRequestController::class, 'viewFeedbackResponse'])->name('requests.rdd.feedback.response');
        Route::get('requests/{serviceRequest}/rdd-request/feedback/responses/{feedbackLink}/pdf', [RddRequestController::class, 'downloadFeedbackResponsePdf'])->name('requests.rdd.feedback.response.pdf');
        Route::get('requests/{serviceRequest}/processing-request', [ProcessingRequestController::class, 'create'])->name('requests.processing.create');
        Route::post('requests/{serviceRequest}/processing-request', [ProcessingRequestController::class, 'store'])->name('requests.processing.store');
        Route::get('requests/{serviceRequest}/processing-request/attachments/{type}', [ProcessingRequestController::class, 'downloadPaymentAttachment'])->name('requests.processing.attachment');
        Route::get('requests/{serviceRequest}/processing-request/pdf', [ProcessingRequestController::class, 'downloadPdf'])->name('requests.processing.pdf');
        Route::get('requests/{serviceRequest}/processing-request/payment', [ProcessingRequestController::class, 'editPayment'])->name('requests.processing.payment.edit');
        Route::post('requests/{serviceRequest}/processing-request/payment', [ProcessingRequestController::class, 'updatePayment'])->name('requests.processing.payment.update');
        Route::post('requests/{serviceRequest}/processing-request/payment/remind', [ProcessingRequestController::class, 'sendPaymentReminder'])->name('requests.processing.payment.remind');
        Route::get('requests/{serviceRequest}/processing-request/feedback', [ProcessingRequestController::class, 'editFeedback'])->name('requests.processing.feedback.edit');
        Route::post('requests/{serviceRequest}/processing-request/feedback/remind', [ProcessingRequestController::class, 'sendFeedbackReminder'])->name('requests.processing.feedback.remind');
        Route::post('requests/{serviceRequest}/processing-request/feedback/generate-link', [ProcessingRequestController::class, 'generateFeedbackLink'])->name('requests.processing.feedback.generate-link');
        Route::get('requests/{serviceRequest}/processing-request/feedback/responses/{feedbackLink}', [ProcessingRequestController::class, 'viewFeedbackResponse'])->name('requests.processing.feedback.response');
        Route::get('requests/{serviceRequest}/processing-request/feedback/responses/{feedbackLink}/pdf', [ProcessingRequestController::class, 'downloadFeedbackResponsePdf'])->name('requests.processing.feedback.response.pdf');
        Route::get('requests/{serviceRequest}/lab-request', [LabRequestController::class, 'create'])->name('requests.lab.create');
        Route::post('requests/{serviceRequest}/lab-request', [LabRequestController::class, 'store'])->name('requests.lab.store');
        Route::get('requests/{serviceRequest}/lab-request/attachments/{type}', [LabRequestController::class, 'downloadPaymentAttachment'])->name('requests.lab.attachment');
        Route::get('requests/{serviceRequest}/lab-request/pdf', [LabRequestController::class, 'downloadPdf'])->name('requests.lab.pdf');
        Route::get('requests/{serviceRequest}/lab-request/payment', [LabRequestController::class, 'editPayment'])->name('requests.lab.payment.edit');
        Route::post('requests/{serviceRequest}/lab-request/payment', [LabRequestController::class, 'updatePayment'])->name('requests.lab.payment.update');
        Route::post('requests/{serviceRequest}/lab-request/payment/remind', [LabRequestController::class, 'sendPaymentReminder'])->name('requests.lab.payment.remind');
        Route::get('requests/{serviceRequest}/lab-request/feedback', [LabRequestController::class, 'editFeedback'])->name('requests.lab.feedback.edit');
        Route::post('requests/{serviceRequest}/lab-request/feedback/remind', [LabRequestController::class, 'sendFeedbackReminder'])->name('requests.lab.feedback.remind');
        Route::post('requests/{serviceRequest}/lab-request/feedback/generate-link', [LabRequestController::class, 'generateFeedbackLink'])->name('requests.lab.feedback.generate-link');
        Route::get('requests/{serviceRequest}/lab-request/feedback/responses/{feedbackLink}', [LabRequestController::class, 'viewFeedbackResponse'])->name('requests.lab.feedback.response');
        Route::get('requests/{serviceRequest}/lab-request/feedback/responses/{feedbackLink}/pdf', [LabRequestController::class, 'downloadFeedbackResponsePdf'])->name('requests.lab.feedback.response.pdf');
        Route::get('requests/{serviceRequest}/training-request', [TrainingRequestController::class, 'create'])->name('requests.training.create');
        Route::post('requests/{serviceRequest}/training-request', [TrainingRequestController::class, 'store'])->name('requests.training.store');
        Route::get('requests/{serviceRequest}/training-request/pdf', [TrainingRequestController::class, 'downloadPdf'])->name('requests.training.pdf');
        Route::get('requests/{serviceRequest}/training-request/fee', [TrainingRequestController::class, 'createFee'])->name('requests.training.fee.create');
        Route::post('requests/{serviceRequest}/training-request/fee', [TrainingRequestController::class, 'storeFee'])->name('requests.training.fee.store');
        Route::get('requests/{serviceRequest}/training-request/fee/pdf', [TrainingRequestController::class, 'downloadFeePdf'])->name('requests.training.fee.pdf');
        Route::get('requests/{serviceRequest}/training-request/attachments/{type}', [TrainingRequestController::class, 'downloadPaymentAttachment'])->name('requests.training.attachment');
        Route::get('requests/{serviceRequest}/training-request/payment', [TrainingRequestController::class, 'editPayment'])->name('requests.training.payment.edit');
        Route::post('requests/{serviceRequest}/training-request/payment', [TrainingRequestController::class, 'updatePayment'])->name('requests.training.payment.update');
        Route::post('requests/{serviceRequest}/training-request/payment/remind', [TrainingRequestController::class, 'sendPaymentReminder'])->name('requests.training.payment.remind');
        Route::get('requests/{serviceRequest}/training-request/feedback', [TrainingRequestController::class, 'editFeedback'])->name('requests.training.feedback.edit');
        Route::post('requests/{serviceRequest}/training-request/feedback/remind', [TrainingRequestController::class, 'sendFeedbackReminder'])->name('requests.training.feedback.remind');
        Route::post('requests/{serviceRequest}/training-request/feedback/generate-link', [TrainingRequestController::class, 'generateFeedbackLink'])->name('requests.training.feedback.generate-link');
        Route::get('requests/{serviceRequest}/training-request/feedback/responses/{feedbackLink}', [TrainingRequestController::class, 'viewFeedbackResponse'])->name('requests.training.feedback.response');
        Route::get('requests/{serviceRequest}/training-request/feedback/responses/{feedbackLink}/pdf', [TrainingRequestController::class, 'downloadFeedbackResponsePdf'])->name('requests.training.feedback.response.pdf');
        Route::get('roles-and-permissions', [AdminManagementController::class, 'roles'])->name('roles');
        Route::get('roles-and-permissions/create', [AdminManagementController::class, 'createRole'])->name('roles.create');
        Route::get('roles-and-permissions/{role}/edit', [AdminManagementController::class, 'editRole'])->name('roles.edit');
        Route::post('roles-and-permissions', [AdminManagementController::class, 'saveRole'])->name('roles.store');
        Route::put('roles-and-permissions/{role}', [AdminManagementController::class, 'saveRole'])->name('roles.update');
        Route::delete('roles-and-permissions/{role}', [AdminManagementController::class, 'deleteRole'])->name('roles.destroy');
        Route::get('users', [AdminManagementController::class, 'users'])->name('users');
        Route::get('users/create', [AdminManagementController::class, 'createUser'])->name('users.create');
        Route::get('users/{user}/edit', [AdminManagementController::class, 'editUser'])->name('users.edit');
        Route::post('users', [AdminManagementController::class, 'saveUser'])->name('users.store');
        Route::put('users/{user}', [AdminManagementController::class, 'saveUser'])->name('users.update');
        Route::delete('users/{user}', [AdminManagementController::class, 'deleteUser'])->name('users.destroy');
        Route::get('form-templates', [FormTemplateController::class, 'index'])->name('form-templates.index');
        Route::get('form-templates/{formTemplate}/edit', [FormTemplateController::class, 'edit'])->name('form-templates.edit');
        Route::put('form-templates/{formTemplate}', [FormTemplateController::class, 'update'])->name('form-templates.update');
        Route::get('feedback-builder/ratings', [FeedbackRatingController::class, 'index'])->name('feedback-builder.ratings.index');
        Route::get('feedback-builder/ratings/create', [FeedbackRatingController::class, 'create'])->name('feedback-builder.ratings.create');
        Route::get('feedback-builder/ratings/{feedbackRating}/edit', [FeedbackRatingController::class, 'edit'])->name('feedback-builder.ratings.edit');
        Route::post('feedback-builder/ratings', [FeedbackRatingController::class, 'store'])->name('feedback-builder.ratings.store');
        Route::put('feedback-builder/ratings/{feedbackRating}', [FeedbackRatingController::class, 'update'])->name('feedback-builder.ratings.update');
        Route::delete('feedback-builder/ratings/{feedbackRating}', [FeedbackRatingController::class, 'destroy'])->name('feedback-builder.ratings.destroy');
        Route::get('feedback-builder/questions', [FeedbackQuestionController::class, 'index'])->name('feedback-builder.questions.index');
        Route::get('feedback-builder/questions/create', [FeedbackQuestionController::class, 'create'])->name('feedback-builder.questions.create');
        Route::get('feedback-builder/questions/{feedbackQuestion}/edit', [FeedbackQuestionController::class, 'edit'])->name('feedback-builder.questions.edit');
        Route::post('feedback-builder/questions', [FeedbackQuestionController::class, 'store'])->name('feedback-builder.questions.store');
        Route::put('feedback-builder/questions/{feedbackQuestion}', [FeedbackQuestionController::class, 'update'])->name('feedback-builder.questions.update');
        Route::delete('feedback-builder/questions/{feedbackQuestion}', [FeedbackQuestionController::class, 'destroy'])->name('feedback-builder.questions.destroy');
        Route::get('feedback-builder', [FeedbackDimensionController::class, 'index'])->name('feedback-builder.index');
        Route::get('feedback-builder/create', [FeedbackDimensionController::class, 'create'])->name('feedback-builder.create');
        Route::get('feedback-builder/visualize', [FeedbackDimensionController::class, 'visualize'])->name('feedback-builder.visualize');
        Route::get('feedback-builder/visualize/pdf', [FeedbackDimensionController::class, 'downloadPdf'])->name('feedback-builder.visualize.pdf');
        Route::put('feedback-builder/order', [FeedbackDimensionController::class, 'reorder'])->name('feedback-builder.reorder');
        Route::get('feedback-builder/{feedbackDimension}/edit', [FeedbackDimensionController::class, 'edit'])->name('feedback-builder.edit');
        Route::post('feedback-builder', [FeedbackDimensionController::class, 'store'])->name('feedback-builder.store');
        Route::put('feedback-builder/{feedbackDimension}', [FeedbackDimensionController::class, 'update'])->name('feedback-builder.update');
        Route::delete('feedback-builder/{feedbackDimension}', [FeedbackDimensionController::class, 'destroy'])->name('feedback-builder.destroy');
        Route::post('feedback-builder/{feedbackDimension}/items', [FeedbackDimensionController::class, 'storeItem'])->name('feedback-builder.items.store');
        Route::put('feedback-builder/{feedbackDimension}/items/order', [FeedbackDimensionController::class, 'reorderItems'])->name('feedback-builder.items.reorder');
        Route::put('feedback-builder/{feedbackDimension}/items/{feedbackItem}', [FeedbackDimensionController::class, 'updateItem'])->name('feedback-builder.items.update');
        Route::delete('feedback-builder/{feedbackDimension}/items/{feedbackItem}', [FeedbackDimensionController::class, 'destroyItem'])->name('feedback-builder.items.destroy');
        Route::get('smtp-configuration', [AdminManagementController::class, 'smtp'])->name('smtp');
        Route::put('smtp-configuration', [AdminManagementController::class, 'saveSmtp'])->name('smtp.update');
        Route::post('smtp-configuration/test', [AdminManagementController::class, 'testSmtp'])->name('smtp.test');
        Route::get('ulims-configuration', [AdminManagementController::class, 'ulimsSettings'])->name('ulims');
        Route::put('ulims-configuration', [AdminManagementController::class, 'saveUlimsSettings'])->name('ulims.update');
        Route::post('ulims-configuration/test', [AdminManagementController::class, 'testUlimsConnection'])->name('ulims.test');
        Route::get('audit-trails', [AuditTrailController::class, 'index'])->name('audit-trails');
        Route::get('my-account', [AdminManagementController::class, 'account'])->name('account');
        Route::post('my-account', [AdminManagementController::class, 'saveAccount'])->name('account.update');
        Route::get('requests/{serviceRequest}/{service}', [ClientController::class, 'showRequest'])->name('requests.client-detail');
        Route::get('{module}', [AdminModuleController::class, 'show'])->name('modules.show');
    });
});
